/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProtoQuit.java
 *
 * Created on Apr 7, 2010, 4:18:39 PM
 */

package view;

/**
 *
 * @author Nadya
 */
public class ProtoQuit extends javax.swing.JFrame {

    /** Creates new form ProtoQuit */
    public ProtoQuit() {
       
        setUndecorated(true);
        initComponents();
        setSize(170,345);
        setResizable(false);
        java.awt.Dimension screenSize =
                java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-getHeight())/2,
                (screenSize.height-getWidth())/2,
                getHeight(),
                getWidth());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuit1 = new template.PanelQuit();
        cmdQuit = new javax.swing.JButton();
        cmdNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdQuit.setBackground(new java.awt.Color(51, 102, 0));
        cmdQuit.setForeground(new java.awt.Color(255, 255, 255));
        cmdQuit.setText("Quit");
        cmdQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuitActionPerformed(evt);
            }
        });

        cmdNo.setBackground(new java.awt.Color(51, 102, 0));
        cmdNo.setForeground(new java.awt.Color(255, 255, 255));
        cmdNo.setText("No");
        cmdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuit1Layout = new javax.swing.GroupLayout(panelQuit1);
        panelQuit1.setLayout(panelQuit1Layout);
        panelQuit1Layout.setHorizontalGroup(
            panelQuit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuit1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(cmdQuit)
                .addGap(51, 51, 51)
                .addComponent(cmdNo)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelQuit1Layout.setVerticalGroup(
            panelQuit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuit1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(panelQuit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdQuit)
                    .addComponent(cmdNo))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQuit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQuit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdQuitActionPerformed

    private void cmdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdNoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProtoQuit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdNo;
    private javax.swing.JButton cmdQuit;
    private template.PanelQuit panelQuit1;
    // End of variables declaration//GEN-END:variables

}
