/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProtoMainMenu.java
 *
 * Created on Apr 7, 2010, 4:17:31 PM
 */

package view;
import controller.MyTray;
import controller.ProtoInit;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kuuga
 */
public class ProtoMainMenu extends javax.swing.JFrame {
ImageIcon iconBenar=new ImageIcon(getClass().getResource("/image/mainmenu-check-true.png"));
Process pY,pO,pF,pM,pR,pG,pB=null;
MyTray myTray=new MyTray();
String message="";
    /** Creates new form ProtoMainMenu */
    public ProtoMainMenu() {
        setUndecorated(true);
        initComponents();
        setSize(563,648);
        setResizable(false);
        java.awt.Dimension screenSize =
                java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-getHeight())/2,
                (screenSize.height-getWidth())/2,
                getHeight(),
                getWidth());
        yM.setToolTipText("Dengan mengaktifkan ini, maka aplikasi Yahoo! Messenger\n " +
                "akan selalu tertutup jika diaktifkan");
        oracle.setToolTipText("Dengan mengaktifkan ini, maka aplikasi Oracle\n " +
                "akan selalu tertutup jika diaktifkan");
        games.setToolTipText("Dengan mengaktifkan ini, default games \npada windows " +
                "akan selalu tertutup jika diaktifkan");
        reader.setToolTipText("Dengan mengaktifkan ini, maka aplikasi \nAdobe Reader " +
                "akan selalu tertutup jika diaktifkan");
        office.setToolTipText("Dengan mengaktifkan ini, maka aplikasi \nMicrosoft Office " +
                "akan selalu tertutup jika diaktifkan");
        firefox.setToolTipText("Dengan mengaktifkan ini, maka aplikasi \nMozilla Firefox " +
                "akan selalu tertutup jika diaktifkan");
        cmdBurstMode.setToolTipText("Dengan Mengaktifkan ini, kita memasukkan sendiri definisi " +
                "yang akan diblock");
        cmdQuit.setToolTipText("klik untuk keluar dari aplikasi");
        cmdHide.setToolTipText("Klik untuk mengaktifkan aplikasi yang dpilih pada " +
                "Application to Block Panel");
        myTray.AddTrayListener();
        myTray.init();
    }
    public void InitIcon(){

        yM.setSelected(false);
        oracle.setSelected(false);
        games.setSelected(false);
        reader.setSelected(false);
        office.setSelected(false);
        firefox.setSelected(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMainMenu1 = new template.PanelMainMenu();
        panelAlpha1 = new template.panelAlpha();
        reader = new javax.swing.JCheckBox();
        games = new javax.swing.JCheckBox();
        office = new javax.swing.JCheckBox();
        firefox = new javax.swing.JCheckBox();
        oracle = new javax.swing.JCheckBox();
        yM = new javax.swing.JCheckBox();
        cmdHide = new javax.swing.JButton();
        cmdBurstMode = new javax.swing.JButton();
        cmdQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        help = new template.PanelHelp();
        aboutMe = new template.AboutMeIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAlpha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Application to Block", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        reader.setFont(new java.awt.Font("Tahoma", 1, 11));
        reader.setText("Adobe Reader");
        reader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainmenu-check-false.png"))); // NOI18N
        reader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readerMouseClicked(evt);
            }
        });

        games.setFont(new java.awt.Font("Tahoma", 1, 11));
        games.setText("Games");
        games.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainmenu-check-false.png"))); // NOI18N
        games.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamesMouseClicked(evt);
            }
        });

        office.setFont(new java.awt.Font("Tahoma", 1, 11));
        office.setText("Microsoft Office");
        office.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainmenu-check-false.png"))); // NOI18N
        office.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                officeMouseClicked(evt);
            }
        });

        firefox.setFont(new java.awt.Font("Tahoma", 1, 11));
        firefox.setText("Mozilla Firefox");
        firefox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainmenu-check-false.png"))); // NOI18N
        firefox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firefoxMouseClicked(evt);
            }
        });

        oracle.setFont(new java.awt.Font("Tahoma", 1, 11));
        oracle.setText("Oracle");
        oracle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainmenu-check-false.png"))); // NOI18N
        oracle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oracleMouseClicked(evt);
            }
        });

        yM.setFont(new java.awt.Font("Tahoma", 1, 11));
        yM.setText("Yahoo! Messenger");
        yM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainmenu-check-false.png"))); // NOI18N
        yM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAlpha1Layout = new javax.swing.GroupLayout(panelAlpha1);
        panelAlpha1.setLayout(panelAlpha1Layout);
        panelAlpha1Layout.setHorizontalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(games, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(office, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firefox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oracle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        panelAlpha1Layout.setVerticalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(reader)
                .addGap(18, 18, 18)
                .addComponent(games)
                .addGap(18, 18, 18)
                .addComponent(office)
                .addGap(18, 18, 18)
                .addComponent(firefox)
                .addGap(18, 18, 18)
                .addComponent(oracle)
                .addGap(18, 18, 18)
                .addComponent(yM)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        cmdHide.setFont(new java.awt.Font("Tahoma", 1, 14));
        cmdHide.setText("Execute and Hide");
        cmdHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHideActionPerformed(evt);
            }
        });

        cmdBurstMode.setFont(new java.awt.Font("Tahoma", 1, 14));
        cmdBurstMode.setText("Burst Mode Activation");
        cmdBurstMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBurstModeActionPerformed(evt);
            }
        });

        cmdQuit.setFont(new java.awt.Font("Tahoma", 1, 14));
        cmdQuit.setText("Quit Application");
        cmdQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Windows Mode");

        help.setToolTipText("Click to see Help");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help);
        help.setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        aboutMe.setToolTipText("About");
        aboutMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aboutMeLayout = new javax.swing.GroupLayout(aboutMe);
        aboutMe.setLayout(aboutMeLayout);
        aboutMeLayout.setHorizontalGroup(
            aboutMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        aboutMeLayout.setVerticalGroup(
            aboutMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainMenu1Layout = new javax.swing.GroupLayout(panelMainMenu1);
        panelMainMenu1.setLayout(panelMainMenu1Layout);
        panelMainMenu1Layout.setHorizontalGroup(
            panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenu1Layout.createSequentialGroup()
                .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdBurstMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdHide, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainMenu1Layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(aboutMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMainMenu1Layout.setVerticalGroup(
            panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenu1Layout.createSequentialGroup()
                .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(panelAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cmdHide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdBurstMode)
                        .addGap(244, 244, 244)
                        .addComponent(cmdQuit)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerMouseClicked
        // TODO add your handling code here:
        reader.setSelectedIcon(iconBenar);
    }//GEN-LAST:event_readerMouseClicked

    private void gamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamesMouseClicked
        // TODO add your handling code here:
        games.setSelectedIcon(iconBenar);
    }//GEN-LAST:event_gamesMouseClicked

    private void officeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officeMouseClicked
        // TODO add your handling code here:
        office.setSelectedIcon(iconBenar);
    }//GEN-LAST:event_officeMouseClicked

    private void firefoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firefoxMouseClicked
        // TODO add your handling code here:
        firefox.setSelectedIcon(iconBenar);
    }//GEN-LAST:event_firefoxMouseClicked

    private void oracleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracleMouseClicked
        // TODO add your handling code here:
        oracle.setSelectedIcon(iconBenar);
    }//GEN-LAST:event_oracleMouseClicked

    private void yMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMMouseClicked
        // TODO add your handling code here:
        yM.setSelectedIcon(iconBenar);
    }//GEN-LAST:event_yMMouseClicked

    private void cmdHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHideActionPerformed
        // TODO add your handling code here:
        try {

           if(yM.isSelected()==true){
           pY=Runtime.getRuntime().exec("/Cerberus/data/msnkillz.exe");
           message=message+"Yahoo\n";
        }

        if(firefox.isSelected()==true){
          pF=Runtime.getRuntime().exec("/Cerberus/data/mozkillz.exe");
          message=message+"Firefox\n";
        }

        if(reader.isSelected()==true){
           pR=Runtime.getRuntime().exec("/Cerberus/data/rderkillz.exe");
           message=message+"Adobe Reader\n";
        }

        if(games.isSelected()==true){
            pG=Runtime.getRuntime().exec("/Cerberus/data/gameskillz.exe");
            message=message+"Default Games\n";
        }

        if(office.isSelected()==true){

           pM=Runtime.getRuntime().exec("/Cerberus/data/officekillz.exe");
           message=message+"Microsoft Office\n";

        }

        if(oracle.isSelected()==true){
            pO=Runtime.getRuntime().exec("/Cerberus/data/orckillz.exe");
            message=message+"Oracle\n";
        }

        if(yM.isSelected()==false && oracle.isSelected()==false && office.isSelected()==false && 
                    reader.isSelected()==false &&games.isSelected()==false
                    && firefox.isSelected()==false ){
            JOptionPane.showMessageDialog(null,"Pilih aplikasi yang ingin dibatasi!","Warning",JOptionPane.YES_OPTION);
            }else{
            setVisible(false);
            /*Bagian Ok*/
            myTray.AddTrayIcon();
            /*Bagian Ok*/
            myTray.showMessageAll(message);

     }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,"terdapat error:"+e.getMessage());
            InitIcon();
            ProtoInit.call();
            message="";
        }
    }//GEN-LAST:event_cmdHideActionPerformed

    private void cmdBurstModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBurstModeActionPerformed
        // TODO add your handling code here:
        try {
                        
                        this.setVisible(false);
                        pB=Runtime.getRuntime().exec("/Cerberus/data/burstkillz.exe");
                        myTray.AddTrayIcon();
                        myTray.showMessageBurstMode();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Terdapat error:"+e);
            InitIcon();
            ProtoInit.call();
            message="";
        }
    }//GEN-LAST:event_cmdBurstModeActionPerformed

    private void cmdQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuitActionPerformed
        // TODO add your handling code here:
        ProtoQuit protoQuit=new ProtoQuit();
        protoQuit.show();
    }//GEN-LAST:event_cmdQuitActionPerformed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
        ProtoHelp protoHelp=new ProtoHelp();
        protoHelp.setHelp("Windows");
        protoHelp.show();
    }//GEN-LAST:event_helpMouseClicked

    private void aboutMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMeMouseClicked
        // TODO add your handling code here:
        ProtoAbout protoAbout=new ProtoAbout();
        protoAbout.show();
    }//GEN-LAST:event_aboutMeMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProtoMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private template.AboutMeIcon aboutMe;
    private javax.swing.JButton cmdBurstMode;
    private javax.swing.JButton cmdHide;
    private javax.swing.JButton cmdQuit;
    private javax.swing.JCheckBox firefox;
    private javax.swing.JCheckBox games;
    private template.PanelHelp help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox office;
    private javax.swing.JCheckBox oracle;
    private template.panelAlpha panelAlpha1;
    private template.PanelMainMenu panelMainMenu1;
    private javax.swing.JCheckBox reader;
    private javax.swing.JCheckBox yM;
    // End of variables declaration//GEN-END:variables

}
