/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProtoHelp.java
 *
 * Created on May 22, 2010, 8:59:05 PM
 */

package view;

/**
 *
 * @author Nadya
 */
public class ProtoHelp extends javax.swing.JFrame {

    /** Creates new form ProtoHelp */

    public ProtoHelp() {
        setUndecorated(true);
        initComponents();
        setSize(360,432);
        setResizable(false);
        java.awt.Dimension screenSize =
                java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-getHeight())/2,
                (screenSize.height-getWidth())/2,
                getHeight(),
                getWidth());
        txtHelp.setEnabled(false);
        txtHelp.setEditable(false);
        
    }
    String helpWin="(**HELP**)\n" +
                "Menu pada System Panel\n" +
                "\n" +
                "*Default*\n" +
                "yakni menampilkan aplikasi - aplikasi standar\n" +
                "yang terdapat pada kebanyakan laboratorium ILKOM\n" +
                "Universitas Gunadarma yang ingin diblock.\n" +
                "pengaktifannya cukup check pada checkbox aplikasi\n" +
                "kemudian klik tombol execute and hide untuk\n" +
                "menjalankan aplikasi secara background.\n" +
                "\n" +
                "*User Defined Burst Mode*\n" +
                "Digunakan untuk mebuat mengaktifkan sebuah user-\n" +
                "defined blocker.\n" +
                "penggunaannya cukup mudah,cukup klik tombol user defined\n" +
                "kemudian masukkan caption- caption program yang ingin\n" +
                "diblock,selanjutnya klik tombol start application\n" +
                "maka aplikasi akan aktif di background.\n" +
                "\n" +
                "*note:user defined burst mode hanya menyimpan konfigurasi\n" +
                "caption saat itu saja,tidak menyimpannya menjadi profile.";
        String helpLin="(**HELP**)\n" +
                "**Linux Mode\n" +
                "\n" +
                "Pada mode ini cukup Masukkan nama aplikasi yang\n" +
                "ingin diblock pada textbox dan tekan tombol add\n" +
                "untuk menambah list dari nama aplikasi yang ingin\n" +
                "diblock.\n" +
                "tekan clear untuk menghapus list satu persatu dari\n" +
                "index terakhir atau klik pada item pada list kemudian\n" +
                "tekan tombol clear untuk menghapus item tertentu.\n" +
                "Untuk menghapus semua isi list, klik Clear All\n" +
                "Untuk Menjalankan aplikasi dengan nama aplikasi yang\n" +
                "ingin diblock sudah terdefinisi pada list, tekan tombol\n" +
                "Execuite and Hide\n" +
                "Untuk keluar tekan tombol Quit";

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProf1 = new template.PanelProf();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHelp = new javax.swing.JTextArea();
        panelHelp1 = new template.PanelHelp();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtHelp.setColumns(20);
        txtHelp.setRows(5);
        txtHelp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtHelp);

        javax.swing.GroupLayout panelHelp1Layout = new javax.swing.GroupLayout(panelHelp1);
        panelHelp1.setLayout(panelHelp1Layout);
        panelHelp1Layout.setHorizontalGroup(
            panelHelp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        panelHelp1Layout.setVerticalGroup(
            panelHelp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ext.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HELP");

        javax.swing.GroupLayout panelProf1Layout = new javax.swing.GroupLayout(panelProf1);
        panelProf1.setLayout(panelProf1Layout);
        panelProf1Layout.setHorizontalGroup(
            panelProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProf1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProf1Layout.createSequentialGroup()
                        .addGroup(panelProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelProf1Layout.setVerticalGroup(
            panelProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProf1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGroup(panelProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProf1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProf1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
    public void setHelp(String status){
        if (status.equalsIgnoreCase("Linux")){
            txtHelp.setText(helpLin);
        }else{
            txtHelp.setText(helpWin);
        }
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProtoHelp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private template.PanelHelp panelHelp1;
    private template.PanelProf panelProf1;
    private javax.swing.JTextArea txtHelp;
    // End of variables declaration//GEN-END:variables

}
