/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProtoMainMenuLinux.java
 *
 * Created on Apr 12, 2010, 12:39:20 AM
 */

package view;

import controller.CerberusPy;
import controller.MyTray;
import javax.swing.*;
/**
 *
 * @author kuuga
 */
public class ProtoMainMenuLinux extends javax.swing.JFrame {
    MyTray myTray=new MyTray();
    /** Creates new form ProtoMainMenuLinux */
    public ProtoMainMenuLinux() {
        setUndecorated(true);

        initComponents();
        setSize(447,734);
        setResizable(false);
        java.awt.Dimension screenSize =
                java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-getHeight())/2,
                (screenSize.height-getWidth())/2,
                getHeight(),
                getWidth());
        lstApp.setModel(defaultListModel);
        myTray.AddTrayListener();
        myTray.init();
        txtApp.requestFocus();
    }

    DefaultListModel defaultListModel=new DefaultListModel();
    String[]items=new String[8];
    int index=0;
    String message="";
    int size=defaultListModel.getSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMainMenu1 = new template.PanelMainMenu();
        panelAlpha1 = new template.panelAlpha();
        jLabel1 = new javax.swing.JLabel();
        txtApp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstApp = new javax.swing.JList();
        cmdAdd = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        cmdClearAll = new javax.swing.JButton();
        cmdExecute = new javax.swing.JButton();
        cmdQuit = new javax.swing.JButton();
        lblStat = new javax.swing.JLabel();
        panelHelp1 = new template.PanelHelp();
        aboutMeIcon1 = new template.AboutMeIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMainMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMainMenu1MouseClicked(evt);
            }
        });

        panelAlpha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cerberus Main", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(242, 247, 245))); // NOI18N

        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel1.setText("Application Name");

        jScrollPane1.setViewportView(lstApp);

        cmdAdd.setText("Add");
        cmdAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdAddMouseClicked(evt);
            }
        });
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdClear.setText("Clear");
        cmdClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdClearMouseClicked(evt);
            }
        });
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        cmdClearAll.setText("Clear All");
        cmdClearAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdClearAllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAlpha1Layout = new javax.swing.GroupLayout(panelAlpha1);
        panelAlpha1.setLayout(panelAlpha1Layout);
        panelAlpha1Layout.setHorizontalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAlpha1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApp))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(cmdAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(cmdClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAlpha1Layout.setVerticalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAdd))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha1Layout.createSequentialGroup()
                        .addComponent(cmdClear)
                        .addGap(18, 18, 18)
                        .addComponent(cmdClearAll))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cmdExecute.setText("Execute and Hide");
        cmdExecute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdExecuteMouseClicked(evt);
            }
        });
        cmdExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExecuteActionPerformed(evt);
            }
        });

        cmdQuit.setText("Quit");
        cmdQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuitActionPerformed(evt);
            }
        });

        lblStat.setForeground(new java.awt.Color(246, 249, 246));
        lblStat.setText("Linux Mode");

        panelHelp1.setToolTipText("Click to see Help");
        panelHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHelp1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelHelp1Layout = new javax.swing.GroupLayout(panelHelp1);
        panelHelp1.setLayout(panelHelp1Layout);
        panelHelp1Layout.setHorizontalGroup(
            panelHelp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        panelHelp1Layout.setVerticalGroup(
            panelHelp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        aboutMeIcon1.setToolTipText("About");
        aboutMeIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMeIcon1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aboutMeIcon1Layout = new javax.swing.GroupLayout(aboutMeIcon1);
        aboutMeIcon1.setLayout(aboutMeIcon1Layout);
        aboutMeIcon1Layout.setHorizontalGroup(
            aboutMeIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        aboutMeIcon1Layout.setVerticalGroup(
            aboutMeIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainMenu1Layout = new javax.swing.GroupLayout(panelMainMenu1);
        panelMainMenu1.setLayout(panelMainMenu1Layout);
        panelMainMenu1Layout.setHorizontalGroup(
            panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addComponent(panelAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdQuit, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelMainMenu1Layout.createSequentialGroup()
                                    .addComponent(aboutMeIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(panelHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmdExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainMenu1Layout.createSequentialGroup()
                        .addComponent(lblStat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        panelMainMenu1Layout.setVerticalGroup(
            panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aboutMeIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHelp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStat)
                .addGap(40, 40, 40)
                .addGroup(panelMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addComponent(panelAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(panelMainMenu1Layout.createSequentialGroup()
                        .addComponent(cmdExecute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                        .addComponent(cmdQuit)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAddMouseClicked
        // TODO add your handling code here:
        
        if(txtApp.getText().trim().equalsIgnoreCase("")/*||txtApp.getText().equalsIgnoreCase(" ")*/){
            JOptionPane.showMessageDialog(null,"Nama Aplikasi tidak boleh kosong!","WARNING",JOptionPane.WARNING_MESSAGE);
            txtApp.setText("");
            txtApp.requestFocus();
        }else{
            if (lstApp.getModel().getSize()<8) {
            items[index]=txtApp.getText();
            defaultListModel.add(index,txtApp.getText());
            index+=1;
            txtApp.setText("");
            txtApp.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null,"Maaf,jumlah aplikasi yang diperbolehkan hanya 8 buah!","WARNING",JOptionPane.WARNING_MESSAGE);
                txtApp.setText("");
                txtApp.requestFocus();
            }
            
        }
        
    }//GEN-LAST:event_cmdAddMouseClicked

    private void cmdExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExecuteActionPerformed
        // TODO add your handling code here:
        if(lstApp.getModel().getSize()==0){
            JOptionPane.showMessageDialog(null,"Masukkan nama aplikasi yang ingin dipilih!","WARNING",JOptionPane.WARNING_MESSAGE);
            txtApp.requestFocus();
        }else{
            for(int id=0;id<items.length;id++){
            if (items[id]==null) {
                items[id]="null";
                                    }
       
                }
        for(int idx=0;idx<lstApp.getModel().getSize();idx++ ){
        message=message+lstApp.getModel().getElementAt(idx)+" \n";
        }

        myTray.AddTrayIcon();
        myTray.showMessageAll(message);
        CerberusPy.kill(items);
        this.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_cmdExecuteActionPerformed

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmdClearActionPerformed

    private void cmdClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdClearMouseClicked
        // TODO add your handling code here:
        
        int selectIdx=lstApp.getSelectedIndex();
        int pos=lstApp.getModel().getSize();
        try {
            if(size==0){
                JOptionPane.showMessageDialog(null,"List kosong!","WARNING",JOptionPane.WARNING_MESSAGE);
                txtApp.requestFocus();
            }else{
                if(selectIdx<0){
                    pos=defaultListModel.getSize()-1;
                    if(pos>=0){
                    defaultListModel.remove(pos);
                    index-=1;
                    }
                }
                else{
                    defaultListModel.remove(selectIdx);
                    index-=1;
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error!:"+e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        txtApp.setText("");
        txtApp.requestFocus();

    }//GEN-LAST:event_cmdClearMouseClicked

    private void cmdClearAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdClearAllMouseClicked
        // TODO add your handling code here:
         if(size==0){
                JOptionPane.showMessageDialog(null,"List kosong!","WARNING",JOptionPane.WARNING_MESSAGE);
                txtApp.requestFocus();
         }else{
            defaultListModel.clear();
            index=0;
            txtApp.setText("");
            txtApp.requestFocus();
            }
        
    }//GEN-LAST:event_cmdClearAllMouseClicked

    private void cmdQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuitActionPerformed
        // TODO add your handling code here:
        ProtoQuit protoQuit=new ProtoQuit();
        protoQuit.show();
        
    }//GEN-LAST:event_cmdQuitActionPerformed
public void init(){
    txtApp.setText("");
    txtApp.requestFocus();
}
    private void cmdExecuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExecuteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdExecuteMouseClicked

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdAddActionPerformed

    private void panelMainMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMainMenu1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelMainMenu1MouseClicked

    private void panelHelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHelp1MouseClicked
        // TODO add your handling code here:
        ProtoHelp protoHelp=new ProtoHelp();
        protoHelp.setHelp("Linux");
        protoHelp.show();
        
    }//GEN-LAST:event_panelHelp1MouseClicked

    private void aboutMeIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMeIcon1MouseClicked
        // TODO add your handling code here:
        ProtoAbout protoAbout=new ProtoAbout();
        protoAbout.show();
    }//GEN-LAST:event_aboutMeIcon1MouseClicked
   
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProtoMainMenuLinux().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private template.AboutMeIcon aboutMeIcon1;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdClearAll;
    private javax.swing.JButton cmdExecute;
    private javax.swing.JButton cmdQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStat;
    private javax.swing.JList lstApp;
    private template.panelAlpha panelAlpha1;
    private template.PanelHelp panelHelp1;
    private template.PanelMainMenu panelMainMenu1;
    private javax.swing.JTextField txtApp;
    // End of variables declaration//GEN-END:variables

}
